import { TelegramUserClient, type TelegramClientConfig } from "../client.js";
import { Api } from "telegram";
import type { NewMessageEvent } from "telegram/events/NewMessage.js";
import { createLogger } from "../../utils/logger.js";
import { withFloodRetry } from "../flood-retry.js";
import { randomLong } from "../../utils/gramjs-bigint.js";
import { classifyMedia } from "../bridge-interface.js";
import { outgoingTracker } from "../outgoing-tracker.js";
import { extractSentMessageResult, isDefiniteSendFailure } from "../send-result.js";
import type {
  ITelegramBridge,
  TelegramMessage,
  InlineButton, // eslint-disable-line @typescript-eslint/no-unused-vars -- re-exported for backward compat
  ParsedButton,
  SendMessageOptions,
  SentMessage,
  EditMessageOptions,
  ReplyContext,
  BotInfo,
  ChatInfo,
} from "../bridge-interface.js";
import type { GiftEvent } from "../../domain/commerce/gift-event.js";

export type { TelegramMessage, InlineButton, SendMessageOptions } from "../bridge-interface.js";

const log = createLogger("Telegram");

/** Max time to wait for getSender() before giving up (deleted accounts, timeouts). */
const SENDER_RESOLVE_TIMEOUT_MS = 5000;

export class GramJSUserBridge implements ITelegramBridge {
  private client: TelegramUserClient;
  private ownUserId?: bigint;
  private ownUsername?: string;
  private peerCache: Map<string, Api.TypePeer> = new Map();

  constructor(config: TelegramClientConfig) {
    this.client = new TelegramUserClient(config);

    // Authoritative acknowledgement stream: whenever Telegram pushes an
    // UpdateMessageID for one of our sends (raw update stream), bind the
    // random_id → message_id mapping BEFORE the outgoing NewMessage event
    // reaches the regular handler pipeline.
    this.client.addUpdateMessageIdHandler((update) => {
      if (update.randomId === undefined) return;
      outgoingTracker.acknowledge(BigInt(update.randomId.toString()), update.id);
    });
  }

  /** Cache a chat's peer for later resolution, evicting the oldest past a cap. */
  private cachePeer(chatId: string, peer: Api.TypePeer): void {
    this.peerCache.set(chatId, peer);
    if (this.peerCache.size > 5000) {
      const oldest = this.peerCache.keys().next().value;
      if (oldest !== undefined) this.peerCache.delete(oldest);
    }
  }

  getMode(): "user" | "bot" {
    return "user";
  }

  requiresOffsetDedup(): boolean {
    return true;
  }

  async connect(): Promise<void> {
    await this.client.connect();
    const me = this.client.getMe();
    if (me) {
      this.ownUserId = me.id;
      this.ownUsername = me.username?.toLowerCase();
    }

    outgoingTracker.startCleanup();

    try {
      await this.getDialogs();
    } catch (error) {
      log.warn({ err: error }, "Could not load dialogs");
    }
  }

  async disconnect(): Promise<void> {
    outgoingTracker.stopCleanup();
    outgoingTracker.clear();
    await this.client.disconnect();
  }

  isAvailable(): boolean {
    return this.client.isConnected();
  }

  getOwnUserId(): bigint | undefined {
    return this.ownUserId;
  }

  getUsername(): string | undefined {
    const me = this.client.getMe();
    return me?.username;
  }

  async getMe(): Promise<BotInfo | undefined> {
    const me = this.client.getMe();
    if (!me) return undefined;
    return {
      id: Number(me.id),
      username: me.username,
      firstName: me.firstName ?? "Unknown",
      isBot: me.isBot,
    };
  }

  async getMessages(chatId: string, limit: number = 50): Promise<TelegramMessage[]> {
    try {
      const peer = this.peerCache.get(chatId) || chatId;
      const messages = await this.client.getMessages(peer, { limit });
      const results = await Promise.allSettled(messages.map((msg) => this.parseMessage(msg)));
      return results
        .filter((r): r is PromiseFulfilledResult<TelegramMessage> => r.status === "fulfilled")
        .map((r) => r.value);
    } catch (error) {
      log.error({ err: error }, "Error getting messages");
      return [];
    }
  }

  /**
   * Run a tracked send: one logical send, one transport randomId.
   *
   * The randomId is generated by the caller BEFORE any network activity and
   * reused verbatim by every flood-retry attempt, so a retry of the same
   * logical send is idempotent at the MTProto level (Telegram dedupes by
   * random_id within its window).
   */
  private async runTrackedSend(
    chatId: string,
    randomId: bigint,
    sendFn: () => Promise<Api.TypeUpdates>
  ): Promise<SentMessage> {
    outgoingTracker.markSending(randomId);
    try {
      const result = await withFloodRetry(sendFn, undefined, undefined, chatId);
      const sent = extractSentMessageResult(result, randomId);
      if (!sent) {
        // Telegram accepted the request but we could not extract the
        // message id — the correlation is ambiguous, keep it for recovery.
        const error = new Error(
          "Send completed but no message id could be extracted from the RPC result"
        );
        outgoingTracker.markAmbiguousFailure(randomId, error);
        throw error;
      }
      outgoingTracker.acknowledge(randomId, sent.messageId, chatId);
      return { id: sent.messageId, date: sent.date, chatId, randomId };
    } catch (error) {
      if (isDefiniteSendFailure(error)) {
        outgoingTracker.markDefiniteFailure(randomId, error);
      } else {
        outgoingTracker.markAmbiguousFailure(randomId, error);
      }
      throw error;
    }
  }

  async sendMessage(
    options: SendMessageOptions & { _rawPeer?: Api.TypePeer }
  ): Promise<SentMessage> {
    const peer = options._rawPeer || this.peerCache.get(options.chatId) || options.chatId;
    const randomId = randomLong();
    outgoingTracker.reserve(options.chatId, randomId);

    const replyMarkup =
      options.inlineKeyboard && options.inlineKeyboard.length > 0
        ? this.buildInlineMarkup(options.inlineKeyboard)
        : undefined;

    return this.runTrackedSend(options.chatId, randomId, () =>
      this.client.sendMessageLowLevel(peer, {
        message: options.text,
        randomId,
        replyTo: options.replyToId,
        replyMarkup,
      })
    );
  }

  /** Build a GramJS inline-keyboard markup from the bridge's button rows. */
  private buildInlineMarkup(
    inlineKeyboard: Array<Array<{ text: string; callback_data: string }>>
  ): Api.ReplyInlineMarkup {
    return new Api.ReplyInlineMarkup({
      rows: inlineKeyboard.map(
        (row) =>
          new Api.KeyboardButtonRow({
            buttons: row.map(
              (btn) =>
                new Api.KeyboardButtonCallback({
                  text: btn.text,
                  data: Buffer.from(btn.callback_data),
                })
            ),
          })
      ),
    });
  }

  async editMessage(options: EditMessageOptions): Promise<SentMessage> {
    try {
      const peer = this.peerCache.get(options.chatId) || options.chatId;

      let buttons: Api.ReplyInlineMarkup | undefined;
      if (options.inlineKeyboard && options.inlineKeyboard.length > 0) {
        buttons = this.buildInlineMarkup(options.inlineKeyboard);
      }

      const gramJsClient = this.client.getClient();
      const result = await withFloodRetry(
        () =>
          gramJsClient.invoke(
            new Api.messages.EditMessage({
              peer,
              id: options.messageId,
              message: options.text,
              replyMarkup: buttons,
            })
          ),
        undefined,
        undefined,
        options.chatId
      );

      let msg: Api.Message | undefined;
      if (result instanceof Api.Updates) {
        const messageUpdate = result.updates.find(
          (u) => u.className === "UpdateEditMessage" || u.className === "UpdateEditChannelMessage"
        );
        if (messageUpdate && "message" in messageUpdate) {
          msg = messageUpdate.message as Api.Message;
        }
      }

      if (msg) {
        return { id: msg.id, date: msg.date, chatId: options.chatId };
      }
      return { id: options.messageId, date: Math.floor(Date.now() / 1000), chatId: options.chatId };
    } catch (error) {
      log.error({ err: error }, "Error editing message");
      throw error;
    }
  }

  async deleteMessage(chatId: string, messageId: number): Promise<boolean> {
    try {
      const gramJsClient = this.client.getClient();
      const isChannel = chatId.startsWith("-100");

      if (isChannel) {
        const channel = await gramJsClient.getEntity(chatId);
        await gramJsClient.invoke(
          new Api.channels.DeleteMessages({
            channel,
            id: [messageId],
          })
        );
      } else {
        await gramJsClient.invoke(
          new Api.messages.DeleteMessages({
            id: [messageId],
            revoke: true,
          })
        );
      }
      return true;
    } catch (error) {
      log.error({ err: error }, "Error deleting message");
      return false;
    }
  }

  async forwardMessage(
    fromChatId: string,
    toChatId: string,
    messageId: number
  ): Promise<SentMessage> {
    const randomId = randomLong();
    outgoingTracker.reserve(toChatId, randomId);

    return this.runTrackedSend(toChatId, randomId, () =>
      this.client.forwardMessagesLowLevel(fromChatId, toChatId, [messageId], [randomId])
    );
  }

  async sendPhoto(
    chatId: string,
    photo: string | Buffer,
    caption?: string,
    replyToId?: number
  ): Promise<SentMessage> {
    const randomId = randomLong();
    outgoingTracker.reserve(chatId, randomId);

    let media: Api.TypeInputMedia;
    try {
      media = await this.client.buildInputMedia({ file: photo });
    } catch (error) {
      // Upload failed before any SendMedia request — nothing was sent.
      outgoingTracker.markDefiniteFailure(randomId, error);
      throw error;
    }

    return this.runTrackedSend(chatId, randomId, () =>
      this.client.sendMediaLowLevel(chatId, {
        media,
        message: caption,
        randomId,
        replyTo: replyToId,
      })
    );
  }

  async sendVideo(
    chatId: string,
    video: string | Buffer,
    opts?: {
      caption?: string;
      replyToId?: number;
      duration?: number;
      width?: number;
      height?: number;
    }
  ): Promise<SentMessage> {
    const randomId = randomLong();
    outgoingTracker.reserve(chatId, randomId);

    let media: Api.TypeInputMedia;
    try {
      media = await this.client.buildInputMedia({
        file: video,
        forceDocument: false,
        supportsStreaming: true,
        attributes: [
          new Api.DocumentAttributeVideo({
            roundMessage: false,
            supportsStreaming: true,
            duration: opts?.duration ?? 0,
            w: opts?.width ?? 0,
            h: opts?.height ?? 0,
          }),
        ],
      });
    } catch (error) {
      outgoingTracker.markDefiniteFailure(randomId, error);
      throw error;
    }

    return this.runTrackedSend(chatId, randomId, () =>
      this.client.sendMediaLowLevel(chatId, {
        media,
        message: opts?.caption,
        randomId,
        replyTo: opts?.replyToId,
      })
    );
  }

  async sendVideoNote(
    chatId: string,
    videoNote: string | Buffer,
    opts?: { caption?: string; replyToId?: number; duration?: number }
  ): Promise<SentMessage> {
    const randomId = randomLong();
    outgoingTracker.reserve(chatId, randomId);

    let media: Api.TypeInputMedia;
    try {
      media = await this.client.buildInputMedia({
        file: videoNote,
        forceDocument: false,
        videoNote: true,
        attributes: [
          new Api.DocumentAttributeVideo({
            roundMessage: true,
            duration: opts?.duration ?? 0,
            w: 0,
            h: 0,
          }),
        ],
      });
    } catch (error) {
      outgoingTracker.markDefiniteFailure(randomId, error);
      throw error;
    }

    return this.runTrackedSend(chatId, randomId, () =>
      this.client.sendMediaLowLevel(chatId, {
        media,
        message: opts?.caption,
        randomId,
        replyTo: opts?.replyToId,
      })
    );
  }

  async copyMessage(fromChatId: string, toChatId: string, messageId: number): Promise<SentMessage> {
    const gramJsClient = this.client.getClient();
    const randomId = randomLong();
    outgoingTracker.reserve(toChatId, randomId);

    const messages = await gramJsClient.getMessages(fromChatId, { ids: [messageId] });
    if (!messages || messages.length === 0 || !messages[0]) {
      const error = new Error(`Message ${messageId} not found in chat ${fromChatId}`);
      outgoingTracker.markDefiniteFailure(randomId, error);
      throw error;
    }

    const sourceMsg = messages[0];

    if (!sourceMsg.media) {
      // Text-only source: ONE logical send, ONE correlation — send the
      // text with the SAME randomId, without reserving a second one.
      return this.runTrackedSend(toChatId, randomId, () =>
        this.client.sendMessageLowLevel(toChatId, {
          message: sourceMsg.message ?? "",
          randomId,
        })
      );
    }

    let media: Api.TypeInputMedia;
    try {
      const buffer = await gramJsClient.downloadMedia(sourceMsg, {});
      if (!buffer) {
        throw new Error(`Failed to download media from message ${messageId}`);
      }
      media = await this.client.buildInputMedia({
        file: Buffer.isBuffer(buffer)
          ? buffer
          : typeof buffer === "string"
            ? Buffer.from(buffer)
            : Buffer.from(buffer as unknown as ArrayBuffer),
      });
    } catch (error) {
      outgoingTracker.markDefiniteFailure(randomId, error);
      throw error;
    }

    return this.runTrackedSend(toChatId, randomId, () =>
      this.client.sendMediaLowLevel(toChatId, {
        media,
        message: sourceMsg.message ?? undefined,
        randomId,
      })
    );
  }

  async clickButton(chatId: string, messageId: number, button: ParsedButton): Promise<boolean> {
    try {
      const gramJsClient = this.client.getClient();

      if (button.type === "callback" && button.data) {
        const peer = this.peerCache.get(chatId) || chatId;

        await gramJsClient.invoke(
          new Api.messages.GetBotCallbackAnswer({
            peer,
            msgId: messageId,
            data: button.data,
          })
        );
        return true;
      }

      if (button.type === "command" && button.command) {
        await this.sendMessage({ chatId, text: button.command });
        return true;
      }

      log.warn({ chatId, messageId, button }, "Unsupported button type for clickButton");
      return false;
    } catch (error) {
      log.error({ err: error, chatId, messageId }, "Error clicking button");
      return false;
    }
  }

  async setTyping(chatId: string): Promise<void> {
    try {
      await this.client.setTyping(chatId);
    } catch (error) {
      log.error({ err: error }, "Error setting typing");
    }
  }

  async sendReaction(chatId: string, messageId: number, emoji: string): Promise<void> {
    try {
      const peer = this.peerCache.get(chatId) || chatId;

      await withFloodRetry(
        () =>
          this.client.getClient().invoke(
            new Api.messages.SendReaction({
              peer,
              msgId: messageId,
              reaction: [
                new Api.ReactionEmoji({
                  emoticon: emoji,
                }),
              ],
            })
          ),
        undefined,
        undefined,
        chatId
      );
    } catch (error) {
      log.error({ err: error }, "Error sending reaction");
      throw error;
    }
  }

  async pinMessage(chatId: string, messageId: number): Promise<boolean> {
    try {
      const gramJsClient = this.client.getClient();
      await gramJsClient.invoke(
        new Api.messages.UpdatePinnedMessage({
          peer: chatId,
          id: messageId,
        })
      );
      return true;
    } catch (error) {
      log.error({ err: error }, "Error pinning message");
      return false;
    }
  }

  async sendDice(chatId: string, emoji?: string): Promise<SentMessage> {
    const randomId = randomLong();
    outgoingTracker.reserve(chatId, randomId);

    return this.runTrackedSend(chatId, randomId, () =>
      this.client.sendMediaLowLevel(chatId, {
        media: new Api.InputMediaDice({ emoticon: emoji ?? "🎲" }),
        message: "",
        randomId,
      })
    );
  }

  async getChatInfo(chatId: string): Promise<ChatInfo> {
    const gramJsClient = this.client.getClient();
    const entity = await gramJsClient.getEntity(chatId);

    if (entity instanceof Api.User) {
      return {
        id: chatId,
        title: [entity.firstName, entity.lastName].filter(Boolean).join(" ") || undefined,
        type: "private",
        username: entity.username,
      };
    }

    if (entity instanceof Api.Channel) {
      const isSupergroup = entity.megagroup ?? false;
      return {
        id: chatId,
        title: entity.title,
        type: isSupergroup ? "supergroup" : "channel",
        memberCount: entity.participantsCount ?? undefined,
        username: entity.username,
      };
    }

    if (entity instanceof Api.Chat) {
      return {
        id: chatId,
        title: entity.title,
        type: "group",
        memberCount: entity.participantsCount ?? undefined,
      };
    }

    return { id: chatId, type: "private" };
  }

  onNewMessage(
    handler: (message: TelegramMessage) => void | Promise<void>,
    filters?: {
      incoming?: boolean;
      outgoing?: boolean;
      chats?: string[];
    }
  ): void {
    this.client.addNewMessageHandler(
      async (event: NewMessageEvent) => {
        const message = await this.parseMessage(event.message);
        if (message.isOutgoing) {
          message.outgoingOrigin = await outgoingTracker.classifyOutgoing(
            message.chatId,
            message.id
          );
        }
        await handler(message);
      },
      {
        incoming: filters?.incoming,
        outgoing: filters?.outgoing,
        chats: filters?.chats,
      }
    );
  }

  onEditedMessage(
    handler: (message: TelegramMessage) => void | Promise<void>,
    _filters?: {
      incoming?: boolean;
      outgoing?: boolean;
      chats?: string[];
    }
  ): void {
    this.client.addEditedMessageHandler(async (event) => {
      const message = await this.parseMessage(event.message);
      message.isEdited = true;
      if (message.isOutgoing) {
        message.outgoingOrigin = await outgoingTracker.classifyOutgoing(message.chatId, message.id);
      }
      await handler(message);
    });
  }

  async fetchReplyContext(rawMsg: unknown): Promise<ReplyContext | null> {
    try {
      const msg = rawMsg as Api.Message;
      const replyMsg = await Promise.race([
        msg.getReplyMessage(),
        new Promise<undefined>((resolve) => setTimeout(() => resolve(undefined), 5000)),
      ]);
      if (!replyMsg) return null;

      let senderName: string | undefined;
      try {
        const sender = await Promise.race([
          replyMsg.getSender(),
          new Promise<undefined>((resolve) => setTimeout(() => resolve(undefined), 5000)),
        ]);
        if (sender && "firstName" in sender) {
          senderName = (sender.firstName as string) ?? undefined;
        }
        if (sender && "username" in sender && !senderName) {
          senderName = (sender.username as string) ?? undefined;
        }
      } catch {
        // Non-critical
      }

      const replyMsgSenderId = replyMsg.senderId ? BigInt(replyMsg.senderId.toString()) : undefined;
      const isAgent = this.ownUserId !== undefined && replyMsgSenderId === this.ownUserId;

      return {
        text: replyMsg.message || undefined,
        senderName,
        isAgent,
      };
    } catch {
      return null;
    }
  }

  getPeer(chatId: string): Api.TypePeer | undefined {
    return this.peerCache.get(chatId);
  }

  // --- Non-interface methods (user-bridge specific) ---

  /** The GramJS client wrapper. Reach it through the isUserBridge type guard. */
  getClient(): TelegramUserClient {
    return this.client;
  }

  async getDialogs(): Promise<
    Array<{
      id: string;
      title: string;
      isGroup: boolean;
      isChannel: boolean;
    }>
  > {
    try {
      const dialogs = await this.client.getDialogs();
      return dialogs.map((d) => ({
        id: d.id.toString(),
        title: d.title,
        isGroup: d.isGroup,
        isChannel: d.isChannel,
      }));
    } catch (error) {
      log.error({ err: error }, "Error getting dialogs");
      return [];
    }
  }

  onServiceMessage(handler: (message: TelegramMessage) => void | Promise<void>): void {
    this.client.addServiceMessageHandler(async (msg: Api.MessageService) => {
      const message = await this.parseServiceMessage(msg);
      if (message) {
        await handler(message);
      }
    });
  }

  /** Resolve sender username/firstName/bot flag with a timeout; non-fatal on failure. */
  private async resolveSender(
    msg: Api.Message | Api.MessageService
  ): Promise<{ senderUsername?: string; senderFirstName?: string; isBot: boolean }> {
    let senderUsername: string | undefined;
    let senderFirstName: string | undefined;
    let isBot = false;
    try {
      const sender = await Promise.race([
        msg.getSender(),
        new Promise<undefined>((resolve) =>
          setTimeout(() => resolve(undefined), SENDER_RESOLVE_TIMEOUT_MS)
        ),
      ]);
      if (sender && "username" in sender) {
        senderUsername = sender.username ?? undefined;
      }
      if (sender && "firstName" in sender) {
        senderFirstName = sender.firstName ?? undefined;
      }
      if (sender instanceof Api.User) {
        isBot = sender.bot ?? false;
      }
    } catch {
      // getSender() can fail on deleted accounts, timeouts, etc. — non-critical
    }
    return { senderUsername, senderFirstName, isBot };
  }

  /** Extract structured buttons from a message's reply markup. */
  private extractButtons(msg: Api.Message): ParsedButton[][] {
    const markup = (msg as unknown as { replyMarkup?: Api.TypeReplyMarkup }).replyMarkup;
    if (!markup) return [];

    try {
      if (markup instanceof Api.ReplyInlineMarkup) {
        return markup.rows.map((row: Api.KeyboardButtonRow) =>
          row.buttons.map((btn) => {
            if (btn instanceof Api.KeyboardButtonCallback) {
              return {
                text: btn.text,
                data: btn.data,
                type: "callback" as const,
              };
            }
            if (btn instanceof Api.KeyboardButtonUrl) {
              return {
                text: btn.text,
                type: "url" as const,
              };
            }
            if (btn instanceof Api.KeyboardButtonSwitchInline) {
              return {
                text: btn.text,
                type: "switch_inline" as const,
              };
            }
            return {
              text: (btn as { text?: string }).text ?? "?",
              type: "unknown" as const,
            };
          })
        );
      }

      if (markup instanceof Api.ReplyKeyboardMarkup) {
        return markup.rows.map((row: Api.KeyboardButtonRow) =>
          row.buttons.map((btn) => {
            const text = (btn as { text?: string }).text ?? "?";
            return {
              text,
              command: text.startsWith("/") ? text : `/${text.toLowerCase().replace(/\s+/g, "_")}`,
              type: "command" as const,
            };
          })
        );
      }

      return [];
    } catch {
      return [];
    }
  }

  private async parseMessage(msg: Api.Message): Promise<TelegramMessage> {
    const chatId = msg.chatId?.toString() ?? msg.peerId?.toString() ?? "unknown";
    const senderIdBig = msg.senderId ? BigInt(msg.senderId.toString()) : BigInt(0);
    const senderId = Number(senderIdBig);

    let mentionsMe = msg.mentioned ?? false;
    if (!mentionsMe && this.ownUsername && msg.message) {
      mentionsMe = msg.message.toLowerCase().includes(`@${this.ownUsername}`);
    }

    const isChannel = msg.post ?? false;
    const isGroup = !isChannel && chatId.startsWith("-");

    if (msg.peerId) this.cachePeer(chatId, msg.peerId);

    const { senderUsername, senderFirstName, isBot } = await this.resolveSender(msg);

    const { hasMedia, mediaType } = classifyMedia({
      photo: msg.photo,
      video: msg.video,
      audio: msg.audio,
      voice: msg.voice,
      sticker: msg.sticker,
      video_note: (msg as unknown as { videoNote?: unknown }).videoNote ?? msg.videoNote,
      document: msg.document,
    });

    const replyToMsgId = msg.replyToMsgId;

    const buttons = this.extractButtons(msg);

    let text = msg.message ?? "";
    if (!text && msg.media) {
      if (msg.media.className === "MessageMediaDice") {
        const dice = msg.media as Api.MessageMediaDice;
        text = `[Dice: ${dice.emoticon} = ${dice.value}]`;
      } else if (msg.media.className === "MessageMediaGame") {
        const game = msg.media as Api.MessageMediaGame;
        text = `[Game: ${game.game.title}]`;
      } else if (msg.media.className === "MessageMediaPoll") {
        const poll = msg.media as Api.MessageMediaPoll;
        text = `[Poll: ${poll.poll.question.text}]`;
      } else if (msg.media.className === "MessageMediaContact") {
        const contact = msg.media as Api.MessageMediaContact;
        text = `[Contact: ${contact.firstName} ${contact.lastName || ""} - ${contact.phoneNumber}]`;
      } else if (
        msg.media.className === "MessageMediaGeo" ||
        msg.media.className === "MessageMediaGeoLive"
      ) {
        text = `[Location shared]`;
      }
    }

    const senderRank = (msg as unknown as { fromRank?: string }).fromRank || undefined;

    return {
      id: msg.id,
      chatId,
      senderId,
      senderUsername,
      senderFirstName,
      senderRank,
      text,
      isGroup,
      isChannel,
      isBot,
      mentionsMe,
      timestamp: new Date(msg.date * 1000),
      _rawPeer: msg.peerId,
      hasMedia,
      mediaType,
      replyToId: replyToMsgId,
      buttons: buttons.length > 0 ? buttons : undefined,
      isEdited: (msg as unknown as { editDate?: number }).editDate !== undefined,
      isOutgoing: msg.out === true,
      _rawMessage: hasMedia || !!replyToMsgId || buttons.length > 0 ? msg : undefined,
    };
  }

  private async parseServiceMessage(msg: Api.MessageService): Promise<TelegramMessage | null> {
    const action = msg.action;
    if (!action) return null;

    const isGiftAction =
      action instanceof Api.MessageActionStarGiftPurchaseOffer ||
      action instanceof Api.MessageActionStarGiftPurchaseOfferDeclined ||
      action instanceof Api.MessageActionStarGift;
    if (!isGiftAction) return null;
    if (msg.out) return null;

    const chatId = msg.chatId?.toString() ?? msg.peerId?.toString() ?? "unknown";
    const senderIdBig = msg.senderId ? BigInt(msg.senderId.toString()) : BigInt(0);
    const senderId = Number(senderIdBig);
    const timestamp = new Date(msg.date * 1000);

    const { senderUsername, senderFirstName, isBot } = await this.resolveSender(msg);

    let text = "";
    let giftEvent: GiftEvent | undefined;

    if (action instanceof Api.MessageActionStarGiftPurchaseOffer) {
      const gift = action.gift;
      const isUnique = gift instanceof Api.StarGiftUnique;
      const title = gift.title || "Unknown Gift";
      const slug = isUnique ? gift.slug : undefined;
      const num = isUnique ? gift.num : undefined;
      const priceStars = action.price.amount?.toString() || "?";
      const status = action.accepted ? "accepted" : action.declined ? "declined" : "pending";
      const expires = action.expiresAt
        ? new Date(action.expiresAt * 1000).toISOString()
        : "unknown";

      text = `[Gift Offer Received]\n`;
      giftEvent = {
        eventKey: `offer:${msg.id}`,
        chatId,
        senderId,
        senderUsername,
        senderFirstName,
        fromAnonymous: false,
        kind: "gift_offer_received",
        receivedAt: timestamp,
        msgId: msg.id,
        giftTitle: title,
        offerPriceStars: priceStars,
        offerAccepted: action.accepted,
        offerDeclined: action.declined,
        offerExpiresAt: action.expiresAt ? new Date(action.expiresAt * 1000) : undefined,
        offerSlug: slug,
        offerNum: num,
      };

      text += `Offer: ${priceStars} Stars for your NFT "${title}"${num ? ` #${num}` : ""}${slug ? ` (slug: ${slug})` : ""}\n`;
      text += `From: ${senderUsername ? `@${senderUsername}` : senderFirstName || `user:${senderId}`}\n`;
      text += `Expires: ${expires}\n`;
      text += `Status: ${status}\n`;
      text += `Message ID: ${msg.id} — use telegram_resolve_gift_offer(offerMsgId=${msg.id}) to accept or telegram_resolve_gift_offer(offerMsgId=${msg.id}, decline=true) to decline.`;

      log.info(
        `Gift offer received: ${priceStars} Stars for "${title}" from ${senderUsername || senderId}`
      );
    } else if (action instanceof Api.MessageActionStarGiftPurchaseOfferDeclined) {
      const gift = action.gift;
      const isUnique = gift instanceof Api.StarGiftUnique;
      const title = gift.title || "Unknown Gift";
      const slug = isUnique ? gift.slug : undefined;
      const num = isUnique ? gift.num : undefined;
      const priceStars = action.price.amount?.toString() || "?";
      const reason = action.expired ? "expired" : "declined";
      giftEvent = {
        eventKey: `offer_declined:${msg.id}`,
        chatId,
        senderId,
        senderUsername,
        senderFirstName,
        fromAnonymous: false,
        kind: "gift_offer_declined",
        receivedAt: timestamp,
        msgId: msg.id,
        giftTitle: title,
        offerPriceStars: priceStars,
        offerExpired: action.expired,
        offerSlug: slug,
        offerNum: num,
      };

      text = `[Gift Offer ${action.expired ? "Expired" : "Declined"}]\n`;
      text += `Your offer of ${priceStars} Stars for NFT "${title}"${num ? ` #${num}` : ""}${slug ? ` (slug: ${slug})` : ""} was ${reason}.`;

      log.info(`Gift offer ${reason}: ${priceStars} Stars for "${title}"`);
    } else if (action instanceof Api.MessageActionStarGift) {
      const gift = action.gift;
      const title = gift.title || "Unknown Gift";
      const stars = gift instanceof Api.StarGift ? gift.stars?.toString() || "?" : "?";
      const giftMessage = action.message?.text || "";
      const fromAnonymous = action.nameHidden ?? false;

      text = `[Gift Received]\n`;
      text += `Gift: "${title}" (${stars} Stars)${action.upgraded ? " [Upgraded to Collectible]" : ""}\n`;
      text += `From: ${fromAnonymous ? "Anonymous" : senderUsername ? `@${senderUsername}` : senderFirstName || `user:${senderId}`}\n`;
      if (giftMessage) text += `Message: "${giftMessage}"\n`;
      if (action.canUpgrade && action.upgradeStars) {
        text += `This gift can be upgraded to a collectible for ${action.upgradeStars.toString()} Stars.\n`;
      }
      if (action.convertStars) {
        text += `Can be converted to ${action.convertStars.toString()} Stars.`;
      }

      giftEvent = {
        eventKey: `gift:${msg.id}`,
        chatId,
        senderId: fromAnonymous ? 0 : senderId,
        senderUsername: fromAnonymous ? undefined : senderUsername,
        senderFirstName: fromAnonymous ? undefined : senderFirstName,
        fromAnonymous,
        kind: "gift_received",
        receivedAt: timestamp,
        msgId: msg.id,
        giftTitle: title,
        stars,
        giftMessage: giftMessage || undefined,
        upgraded: action.upgraded,
        canUpgrade: action.canUpgrade,
        upgradeStars: action.upgradeStars?.toString(),
        convertStars: action.convertStars?.toString(),
      };

      log.info(
        `Gift received: "${title}" (${stars} Stars) from ${fromAnonymous ? "Anonymous" : senderUsername || senderId}`
      );
    }

    if (!text) return null;

    if (msg.peerId) this.cachePeer(chatId, msg.peerId);

    return {
      id: msg.id,
      chatId,
      senderId,
      senderUsername,
      senderFirstName,
      text: text.trim(),
      isGroup: false,
      isChannel: false,
      isBot,
      mentionsMe: true,
      timestamp,
      hasMedia: false,
      _rawPeer: msg.peerId,
      giftEvent,
    };
  }
}
